# Generated by Django 2.2.4 on 2019-08-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0002_grouppost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPost',
        ),
    ]
