# Generated by Django 2.2.4 on 2019-08-23 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('group_code', models.CharField(max_length=20)),
                ('invitation_url', models.CharField(default=uuid.uuid1, max_length=20, unique=True)),
                ('group_bio', models.CharField(blank=True, default='그룹 소개를 50자 이내(한줄)로 작성해주세요', max_length=300, null=True)),
                ('group_goal', models.CharField(blank=True, default='그룹 목표를 50자 이내(한줄)로 작성해주세요', max_length=50, null=True)),
                ('group_rule', models.CharField(blank=True, default='그룹 규칙을 작성해주세요', max_length=50, null=True)),
                ('late_penalty', models.CharField(default='0', max_length=10)),
                ('abscence_penalty', models.CharField(default='0', max_length=10)),
                ('notsubmit_penalty', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='업데이트 기준')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'MANAGER'), ('STAFF', 'STAFF'), ('MEMBER', 'MEMBER')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('OUT', 'OUT')], default='ACTIVE', max_length=20)),
                ('total_admit', models.IntegerField(default=0, verbose_name='인정 총합')),
                ('total_penalty', models.IntegerField(default=0, verbose_name='벌금 총합')),
                ('penalty_attend', models.IntegerField(default=0, verbose_name='출석 벌금 총합')),
                ('noshow_attend', models.IntegerField(default=0, verbose_name='출석 결석 횟수')),
                ('late_attend', models.IntegerField(default=0, verbose_name='출석 지각 횟수')),
                ('admit_attend', models.IntegerField(default=0, verbose_name='출석 인정')),
                ('penalty_assign', models.IntegerField(default=0, verbose_name='과제 벌금 총합')),
                ('noshow_assign', models.IntegerField(default=0, verbose_name='과제 미제출 횟수')),
                ('admit_assign', models.IntegerField(default=0, verbose_name='과제 인정')),
                ('rank', models.IntegerField(default=0, null=True, verbose_name='등수')),
                ('phone_number_open', models.BooleanField(default=False)),
                ('bio_open', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_member',
            field=models.ManyToManyField(through='study.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
