# Generated by Django 2.2.4 on 2019-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('MEMBER', 'MEMBER')], default='MEMBER', max_length=20),
        ),
    ]
