# Generated by Django 2.2.4 on 2019-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='업데이트 기준'),
        ),
    ]
