# Generated by Django 2.2.4 on 2019-08-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ass_abscence_penalty',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='att_abscence_penalty',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='att_late_penalty',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='group_rule',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
