# Generated by Django 2.2.4 on 2019-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_bio',
            field=models.CharField(blank=True, default='그룹 소개를 50자 이내(한줄)로 작성해주세요', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_rule',
            field=models.CharField(blank=True, default='그룹 규칙을 작성해주세요', max_length=50, null=True),
        ),
    ]
