# Generated by Django 2.2.4 on 2019-08-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='assign_admit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='attend_admit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_admit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_penalty',
            field=models.IntegerField(default=0),
        ),
    ]
