# Generated by Django 2.2.4 on 2019-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='attend_admit',
            field=models.IntegerField(default=0, verbose_name='출석 인정 횟수'),
        ),
        migrations.AddField(
            model_name='membership',
            name='late_num',
            field=models.IntegerField(default=0, verbose_name='출석 지각 횟수'),
        ),
        migrations.AddField(
            model_name='membership',
            name='noshow_num',
            field=models.IntegerField(default=0, verbose_name='출석 결석 횟수'),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_admit',
            field=models.IntegerField(default=0, verbose_name='인정 총합'),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_penalty',
            field=models.IntegerField(default=0, verbose_name='벌금 총합'),
        ),
    ]
