# Generated by Django 2.2.4 on 2019-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20190813_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='ass_abscence_penalty',
            new_name='late_penalty',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='att_abscence_penalty',
            new_name='notsubmit_penalty',
        ),
        migrations.RemoveField(
            model_name='group',
            name='att_late_penalty',
        ),
        migrations.AddField(
            model_name='group',
            name='abscence_penalty',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
