# Generated by Django 2.2.4 on 2019-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20190816_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_bio',
            field=models.CharField(blank=True, default='그룹 설정에서 수정하세요', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_goal',
            field=models.CharField(blank=True, default='그룹 설정에서 수정하세요', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_rule',
            field=models.CharField(blank=True, default='그룹 설정에서 수정하세요', max_length=600, null=True),
        ),
    ]
