# Generated by Django 2.2.4 on 2019-08-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('NEEDS_APPROVAL', 'NEEDS_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('OUT', 'OUT')], default='ACTIVE', max_length=20),
        ),
    ]
