# Generated by Django 2.2.4 on 2019-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='admit',
            field=models.IntegerField(default=0, null=True, verbose_name='인정'),
        ),
        migrations.AddField(
            model_name='membership',
            name='penalty',
            field=models.IntegerField(default=0, null=True, verbose_name='벌금'),
        ),
    ]
