# Generated by Django 2.2.4 on 2019-08-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190809_1729'),
        ('study', '0003_membership_status'),
    ]

    operations = [
    ]
