# Generated by Django 2.2.4 on 2019-08-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_goal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('OUT', 'OUT')], default='ACTIVE', max_length=20),
        ),
    ]
