# Generated by Django 2.2.4 on 2019-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190805_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_code',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
