# Generated by Django 2.2.4 on 2019-08-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20190821_0913'),
        ('study', '0004_auto_20190821_0035'),
        ('study', '0004_auto_20190821_1442'),
    ]

    operations = [
    ]
