# Generated by Django 2.2.4 on 2019-08-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_merge_20190810_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='admit',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='penalty',
        ),
    ]
