# Generated by Django 2.2.4 on 2019-08-22 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_merge_20190822_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='bio_open',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='phone_number_open',
        ),
        migrations.AlterField(
            model_name='group',
            name='abscence_penalty',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_member',
            field=models.ManyToManyField(related_name='joined_groups', through='study.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='late_penalty',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='notsubmit_penalty',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
