# Generated by Django 2.2.4 on 2019-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20190822_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_bio',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField>그룹입니다!', max_length=300, null=True),
        ),
    ]
