# Generated by Django 2.2.4 on 2019-08-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20190822_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='abscence_penalty',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='group',
            name='late_penalty',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='group',
            name='notsubmit_penalty',
            field=models.IntegerField(default='0'),
        ),
    ]
