# Generated by Django 2.2.4 on 2019-08-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20190822_2153'),
        ('study', '0005_auto_20190823_0017'),
    ]

    operations = [
    ]
