# Generated by Django 2.2.4 on 2019-08-23 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_merge_20190823_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_bio',
            field=models.TextField(blank=True, default='그룹 설정에서 수정하세요', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_member',
            field=models.ManyToManyField(through='study.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
