# Generated by Django 2.2.4 on 2019-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='index_in_group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
