# Generated by Django 2.2.4 on 2019-08-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='done',
            name='noinjung',
        ),
    ]
