# Generated by Django 2.2.4 on 2019-08-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_injung_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='done_checked',
            field=models.BooleanField(default=False),
        ),
    ]
