# Generated by Django 2.2.4 on 2019-08-12 22:51

from django.db import migrations, models
import studypost.models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='lnglat',
            field=models.CharField(blank=True, max_length=50, validators=[studypost.models.lnglat_validator]),
        ),
    ]
