# Generated by Django 2.2.4 on 2019-08-11 05:54

from django.db import migrations, models
import studypost.models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='lnglat',
            field=models.CharField(help_text='경도/위도 포맷으로 입력', max_length=50, validators=[studypost.models.lnglat_validator]),
        ),
    ]
