# Generated by Django 2.2.4 on 2019-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
