# Generated by Django 2.2.4 on 2019-08-11 05:56

from django.db import migrations, models
import studypost.models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0002_auto_20190811_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷으로 입력', max_length=50, validators=[studypost.models.lnglat_validator]),
        ),
    ]
