# Generated by Django 2.2.4 on 2019-08-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20190811_1634'),
        ('studypost', '0003_delete_grouppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Group')),
            ],
        ),
    ]
