# Generated by Django 2.2.4 on 2019-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0004_auto_20190815_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='studypost/notice/%Y/%m/%d', verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='studypost/notice/%Y/%m/%d', verbose_name='사진'),
        ),
    ]
