# Generated by Django 2.2.4 on 2019-08-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypost', '0005_auto_20190815_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='studypost/homework/%Y/%m/%d', verbose_name='파일 업로드'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='studypost/homework/%Y/%m/%d', verbose_name='사진'),
        ),
    ]
