# Generated by Django 2.2.4 on 2019-08-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyuser',
            name='nickname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
