# Generated by Django 2.2.4 on 2019-08-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190807_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studyuser',
            name='img_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user'),
        ),
    ]
