# Generated by Django 2.2.4 on 2019-08-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0003_auto_20190809_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=30, verbose_name='출석')),
                ('gather_time', models.DateTimeField(verbose_name='모임시간')),
                ('expired_time', models.IntegerField(verbose_name='만료시간')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AttendConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_user', models.CharField(max_length=20)),
                ('arrive_time', models.DateTimeField()),
                ('sub_time', models.IntegerField()),
                ('attend_check', models.CharField(choices=[('지각', '지각'), ('출석', '출석')], default='지각', max_length=20)),
                ('attendconfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attend')),
            ],
        ),
    ]
