# Generated by Django 2.2.4 on 2019-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendconfirm',
            name='attend_check',
            field=models.CharField(choices=[('없음', '없음'), ('지각', '지각'), ('출석', '출석'), ('결석', '결석')], default='결석', max_length=20),
        ),
    ]
