# Generated by Django 2.2.4 on 2019-08-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='attend',
            name='gather_time',
        ),
        migrations.AddField(
            model_name='attend',
            name='expired_datetime',
            field=models.DateTimeField(default=None, verbose_name='출석 만료시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attend',
            name='gather_datetime',
            field=models.DateTimeField(default=None, verbose_name='모임 날짜와 시간'),
            preserve_default=False,
        ),
    ]
