# Generated by Django 2.2.4 on 2019-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
