# Generated by Django 2.2.4 on 2019-08-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190816_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendconfirm',
            old_name='attendconfirm',
            new_name='attend',
        ),
    ]
