# Generated by Django 2.2.4 on 2019-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attend_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='checked',
        ),
    ]
