# Generated by Django 2.2.4 on 2019-08-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attend_gather_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='gather_date',
        ),
        migrations.AlterField(
            model_name='attend',
            name='attendance_number',
            field=models.CharField(max_length=5, verbose_name='출석확인번호'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='title',
            field=models.CharField(max_length=30, verbose_name='출석 제목'),
        ),
    ]
