# Generated by Django 2.2.4 on 2019-08-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190816_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='attend_data_checked',
            field=models.BooleanField(default=0, verbose_name='결석 처리 여부'),
        ),
    ]
