# Generated by Django 2.2.4 on 2019-08-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attend_attend_data_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendconfirm',
            name='attend_check',
            field=models.CharField(choices=[('출석 정보 없음', '출석 정보 없음'), ('지각', '지각'), ('출석', '출석'), ('결석', '결석')], default='없음', max_length=20),
        ),
    ]
