# Generated by Django 2.2.4 on 2019-08-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20190817_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendconfirm',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='도착 시간'),
        ),
        migrations.AlterField(
            model_name='attendconfirm',
            name='sub_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='시간 차이'),
        ),
    ]
