# Generated by Django 2.2.4 on 2019-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='init_datetime',
            field=models.DateTimeField(default=None, verbose_name='출석가능 시작시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attend',
            name='expired_datetime',
            field=models.DateTimeField(verbose_name='출석가능 만료시간'),
        ),
    ]
