# Generated by Django 2.2.4 on 2019-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attend_attend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='attend_status',
            field=models.CharField(choices=[('출석가능', '출석가능'), ('출석불가', '출석불가')], default=None, max_length=15, null=True),
        ),
    ]
